//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONAutocompleteTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Eventinvitations = new HashSet<Eventinvitation>();
        }
    
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int member_id { get; set; }
        public System.DateTime eventdate { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool viewpublic { get; set; }
        public string location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventinvitation> Eventinvitations { get; set; }
        public virtual Member Member { get; set; }
    }
}
