
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Meets.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BesaetigungDetailView
{

    public string Eventdatum { get; set; }

    public string Eventtitel { get; set; }

    public string Bestätigungszeitpunkt { get; set; }

    public string Eingeladen { get; set; }

    public bool Bestätigt { get; set; }

}

}
