//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cv_OpenPlaces
    {
        public int id { get; set; }
        public Nullable<int> maxConfirms { get; set; }
        public Nullable<int> Confirmed { get; set; }
        public Nullable<int> openPlaces { get; set; }
    }
}
