
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Meets.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public int id { get; set; }

    public System.DateTime created { get; set; }

    public int member_id { get; set; }

    public System.DateTime eventdate { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public bool viewpublic { get; set; }

    public string location { get; set; }



    public virtual Member Member { get; set; }

}

}
