
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Meets.Models
{

using System;
    using System.Collections.Generic;
    
public partial class View_Event
{

    public System.DateTime Erstellt { get; set; }

    public string Ersteller { get; set; }

    public System.DateTime Termin { get; set; }

    public string Veranstaltungsname { get; set; }

    public string Beschreibung { get; set; }

    public bool Oeffentlich { get; set; }

    public string Standort { get; set; }

}

}
