//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropEvent
    {
        public int id { get; set; }
        public int event_id { get; set; }
        public string eventproperty { get; set; }
        public string eventpropvalue { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
